name: Deploy

on:
  pull_request:
    #types: [closed]
    branches:
      - develop
      
jobs:
  deploy:
    runs-on: [ubuntu-latest]
    if: github.event.pull_request.merged
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: API-${{ github.event.number }}
