name: .NET Core

on:
  push:
    branches:
      - CI

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Build with dotnet
      working-directory: P8-API/
      run: dotnet build --configuration Release
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: API
        # Directory containing files to upload
        working-directory: P8-API/P8-API/P8-API/
        path: /bin/Release/netcoreapp3.1/
