name: .NET Core

on:
  pull_request:
    branches: 
      - develop
      - master

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    # Tests
    - name: Tests
      working-directory: P8-API
      run: dotnet test

    # Build
    - name: Build with dotnet
      working-directory: P8-API
      run: dotnet build --configuration Release
    
    # Artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: API-${{ github.event.number }}
        # Directory containing files to upload
        path: /home/runner/work/P8-API/P8-API/P8-API/P8-API/bin/Release/netcoreapp3.1/
