name: .NET Core

on: [push]

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    # Tests
    - name: Tests
      working-directory: P8-API
      run: dotnet test

    # Build
    - name: Build with dotnet
      working-directory: P8-API
      run: dotnet build
