name: .NET Core

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: 
      - develop
      - master

jobs:
  test-and-build:

    runs-on: ubuntu-latest

    steps:
    # Checkout
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    # Tests
    - name: Tests
      working-directory: P8-API
      run: dotnet test

    # Build
    - name: Build with dotnet
      working-directory: P8-API
      run: dotnet build --configuration Release
    
    # Artifact
    - name: Upload Artifact
      if: github.event.pull_request.merged
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: API-${{ github.event.number }}
        # Directory containing files to upload
        path: /home/runner/work/P8-API/P8-API/P8-API/P8-API/bin/Release/netcoreapp3.1/

  deploy:
    needs: [test-and-build]
    runs-on: [ubuntu-latest]
    if: github.event.pull_request.merged
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Artifact name
          name: API-${{ github.event.number }}
      
      - name: Upload Files
        uses: isthatcentered/dist-to-ftp@v1
        with:
          # FTP host
          host: ${{ secrets.HOST }}
          # FTP user
          user: ${{ secrets.USER }}
          # FTP password
          password: ${{ secrets.PASSWORD }}
          # Local directory
          path: API-${{ github.event.number }}
          # Remote directory
          into: API/${{ github.ref }}
          cleanupExisting: true
      
      - name: Restart API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: sudo systemctl restart api-${{ github.ref }}.service
      
      - name: GitHub Actions Artifact Cleaner
        uses: glassechidna/artifact-cleaner@v2
        with:
          name: API-${{ github.event.number }}
    
